In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/santander-customer-satisfaction/sample_submission.csv
/kaggle/input/competitions/santander-customer-satisfaction/train.csv
/kaggle/input/competitions/santander-customer-satisfaction/test.csv

In [2]:
train = pd.read_csv('/kaggle/input/competitions/santander-customer-satisfaction/train.csv')

In [3]:
num_cols = [col for col in train.columns if train[col].nunique() > 2]
num_cols.pop(0)

'ID'

In [4]:
test = pd.read_csv('/kaggle/input/competitions/santander-customer-satisfaction/test.csv')

In [5]:
test

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
0,2,2,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40532.100000
1,5,2,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45486.720000
2,6,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46993.950000
3,7,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,187898.610000
4,9,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,73649.730000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75813,151831,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40243.200000
75814,151832,2,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,146961.300000
75815,151833,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,167299.770000
75816,151834,2,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016
75817,151837,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.set_output(transform='pandas')

StandardScaler()

In [7]:
train[num_cols] = scaler.fit_transform(train[num_cols])

In [8]:
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(threshold=0)
train_reduced = selector.fit_transform(train)

selected_features = train.columns[selector.get_support()]

In [9]:
selected_features_test = selected_features[0:336]

In [10]:
train = train[selected_features]
y = np.array(train['TARGET'])
X = np.array(train.iloc[:,1:336])

test[num_cols] = scaler.transform(test[num_cols])
test = test[selected_features_test]
X_test = np.array(test.iloc[:,1:])
test_keys = test['ID']

In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping

model = keras.Sequential([
    layers.Input(shape=(335,)),
    layers.Dense(32, activation='relu'),
    #layers.BatchNormalization(),
    layers.Dropout(rate=.5),
    layers.Dense(8, activation='relu'),
    layers.Dropout(rate=.4),
    #layers.BatchNormalization(),
    layers.Dense(1, activation='sigmoid')
])

model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=.00005), #1e-6 is probably best, but use like 100 epochs
        loss="binary_crossentropy",
        metrics=[keras.metrics.BinaryAccuracy(name="accuracy"), keras.metrics.AUC(name="auc")]
    )

early_stop = EarlyStopping(
    monitor='val_auc', 
    patience=10, 
    restore_best_weights=True
)

class_weight = {0: 1.0, 1: 10}
model.fit(X, y, epochs=100, batch_size=50, class_weight=class_weight, validation_split=.2, callbacks=[early_stop])

2026-05-03 01:38:22.670915: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777772302.869795      16 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777772302.933764      16 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777772303.419089      16 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777772303.419146      16 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777772303.419149      16 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777772303.419152      16 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-05-03 01:38:47.864314: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Epoch 1/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.3390 - auc: 0.5387 - loss: 309326.9688 - val_accuracy: 0.8177 - val_auc: 0.7230 - val_loss: 165233.6094
Epoch 2/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6216 - auc: 0.5806 - loss: 325962.5000 - val_accuracy: 0.9065 - val_auc: 0.7475 - val_loss: 107306.4453
Epoch 3/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7240 - auc: 0.5967 - loss: 112750.3203 - val_accuracy: 0.9273 - val_auc: 0.7569 - val_loss: 101749.7188
Epoch 4/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7819 - auc: 0.6307 - loss: 164490.7344 - val_accuracy: 0.9338 - val_auc: 0.7680 - val_loss: 93758.6562
Epoch 5/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8164 - auc: 0.6406 - loss: 98467.0312 - val_accuracy: 0.9394 - val_auc: 0.7737 - val_loss: 90643.9141
Epoch 6/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8505 - auc: 0.6528 - loss: 212309.3906 - val_accuracy: 0.9386 - val_auc: 0.7790 - val_loss: 82260.7656
Epoch 7/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8712 - auc: 0.6652 - loss: 118411.3359 - val_accuracy: 0.9368 - val_auc: 0.7823 - val_loss: 79564.5078
Epoch 8/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8820 - auc: 0.6953 - loss: 118641.0000 - val_accuracy: 0.9387 - val_auc: 0.7856 - val_loss: 68610.6328
Epoch 9/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8967 - auc: 0.6804 - loss: 171935.1406 - val_accuracy: 0.9403 - val_auc: 0.7874 - val_loss: 53825.0000
Epoch 10/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9010 - auc: 0.6975 - loss: 99881.2656 - val_accuracy: 0.9403 - val_auc: 0.7898 - val_loss: 49769.8906
Epoch 11/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9058 - auc: 0.7069 - loss: 128398.4922 - val_accuracy: 0.9409 - val_auc: 0.7899 - val_loss: 43006.4141
Epoch 12/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9049 - auc: 0.6997 - loss: 94364.5703 - val_accuracy: 0.9410 - val_auc: 0.7903 - val_loss: 41089.2461
Epoch 13/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9080 - auc: 0.7111 - loss: 95632.6484 - val_accuracy: 0.9421 - val_auc: 0.7920 - val_loss: 40274.6016
Epoch 14/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9096 - auc: 0.7052 - loss: 114845.3281 - val_accuracy: 0.9411 - val_auc: 0.7937 - val_loss: 34208.7148
Epoch 15/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9133 - auc: 0.7178 - loss: 180760.7188 - val_accuracy: 0.9419 - val_auc: 0.7952 - val_loss: 30491.0176
Epoch 16/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9164 - auc: 0.7232 - loss: 73767.1016 - val_accuracy: 0.9398 - val_auc: 0.7956 - val_loss: 27245.1816
Epoch 17/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9151 - auc: 0.7334 - loss: 146570.8750 - val_accuracy: 0.9397 - val_auc: 0.7974 - val_loss: 25544.5430
Epoch 18/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9141 - auc: 0.7381 - loss: 54584.6523 - val_accuracy: 0.9413 - val_auc: 0.7979 - val_loss: 28584.9668
Epoch 19/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9133 - auc: 0.7365 - loss: 50234.1562 - val_accuracy: 0.9426 - val_auc: 0.7994 - val_loss: 28267.5898
Epoch 20/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9156 - auc: 0.7268 - loss: 39744.9688 - val_accuracy: 0.9413 - val_auc: 0.8007 - val_loss: 23073.9688
Epoch 21/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9153 - auc: 0.7348 - loss: 24999.1445 - val_accuracy: 0.9395 - val_auc: 0.8004 - val_loss: 22932.5605
Epoch 22/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9150 - auc: 0.7404 - loss: 30640.0703 - val_accuracy: 0.9427 - val_auc: 0.8018 - val_loss: 22859.1094
Epoch 23/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9154 - auc: 0.7446 - loss: 92069.9375 - val_accuracy: 0.9412 - val_auc: 0.8022 - val_loss: 24230.4531
Epoch 24/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9163 - auc: 0.7408 - loss: 53424.7969 - val_accuracy: 0.9410 - val_auc: 0.8028 - val_loss: 21994.5703
Epoch 25/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9150 - auc: 0.7442 - loss: 79114.9766 - val_accuracy: 0.9430 - val_auc: 0.8023 - val_loss: 22895.1309
Epoch 26/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9175 - auc: 0.7465 - loss: 21860.5840 - val_accuracy: 0.9421 - val_auc: 0.8034 - val_loss: 26934.8945
Epoch 27/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9167 - auc: 0.7507 - loss: 39988.0312 - val_accuracy: 0.9421 - val_auc: 0.8031 - val_loss: 26840.0898
Epoch 28/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9166 - auc: 0.7472 - loss: 24132.7031 - val_accuracy: 0.9419 - val_auc: 0.8036 - val_loss: 25301.9766
Epoch 29/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9162 - auc: 0.7540 - loss: 14402.1992 - val_accuracy: 0.9396 - val_auc: 0.8041 - val_loss: 24900.0723
Epoch 30/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9170 - auc: 0.7537 - loss: 8571.9932 - val_accuracy: 0.9385 - val_auc: 0.8045 - val_loss: 24131.1074
Epoch 31/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9138 - auc: 0.7622 - loss: 23434.0371 - val_accuracy: 0.9386 - val_auc: 0.8046 - val_loss: 22631.2578
Epoch 32/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9180 - auc: 0.7502 - loss: 35454.8281 - val_accuracy: 0.9356 - val_auc: 0.8044 - val_loss: 22903.8438
Epoch 33/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9145 - auc: 0.7600 - loss: 24096.5020 - val_accuracy: 0.9367 - val_auc: 0.8052 - val_loss: 24862.5586
Epoch 34/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9157 - auc: 0.7630 - loss: 36607.0859 - val_accuracy: 0.9363 - val_auc: 0.8054 - val_loss: 23815.5645
Epoch 35/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9155 - auc: 0.7530 - loss: 17684.4883 - val_accuracy: 0.9344 - val_auc: 0.8059 - val_loss: 21588.4355
Epoch 36/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9145 - auc: 0.7684 - loss: 22678.3379 - val_accuracy: 0.9359 - val_auc: 0.8064 - val_loss: 21380.9727
Epoch 37/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9156 - auc: 0.7663 - loss: 43847.8555 - val_accuracy: 0.9359 - val_auc: 0.8065 - val_loss: 19898.7949
Epoch 38/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9188 - auc: 0.7623 - loss: 21584.2988 - val_accuracy: 0.9312 - val_auc: 0.8065 - val_loss: 19975.9531
Epoch 39/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9125 - auc: 0.7621 - loss: 21427.4395 - val_accuracy: 0.9314 - val_auc: 0.8074 - val_loss: 19358.6836
Epoch 40/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9137 - auc: 0.7699 - loss: 16565.6641 - val_accuracy: 0.9328 - val_auc: 0.8071 - val_loss: 19431.0059
Epoch 41/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9172 - auc: 0.7589 - loss: 6319.3467 - val_accuracy: 0.9290 - val_auc: 0.8076 - val_loss: 18058.1367
Epoch 42/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9120 - auc: 0.7591 - loss: 4015.9702 - val_accuracy: 0.9330 - val_auc: 0.8080 - val_loss: 18033.0098
Epoch 43/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9160 - auc: 0.7622 - loss: 13021.6436 - val_accuracy: 0.9293 - val_auc: 0.8079 - val_loss: 13788.2568
Epoch 44/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9177 - auc: 0.7612 - loss: 20224.8203 - val_accuracy: 0.9292 - val_auc: 0.8092 - val_loss: 12849.6533
Epoch 45/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9150 - auc: 0.7666 - loss: 4689.6909 - val_accuracy: 0.9250 - val_auc: 0.8091 - val_loss: 12634.4463
Epoch 46/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9151 - auc: 0.7686 - loss: 7345.8071 - val_accuracy: 0.9260 - val_auc: 0.8096 - val_loss: 13399.5537
Epoch 47/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9148 - auc: 0.7709 - loss: 11901.1855 - val_accuracy: 0.9248 - val_auc: 0.8096 - val_loss: 13116.7275
Epoch 48/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9149 - auc: 0.7745 - loss: 4376.9688 - val_accuracy: 0.9276 - val_auc: 0.8093 - val_loss: 12285.4590
Epoch 49/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9162 - auc: 0.7572 - loss: 11515.0869 - val_accuracy: 0.9289 - val_auc: 0.8100 - val_loss: 12145.4785
Epoch 50/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9165 - auc: 0.7732 - loss: 4268.7642 - val_accuracy: 0.9279 - val_auc: 0.8096 - val_loss: 11215.5830
Epoch 51/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9159 - auc: 0.7761 - loss: 17357.5391 - val_accuracy: 0.9225 - val_auc: 0.8100 - val_loss: 9224.0215
Epoch 52/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9114 - auc: 0.7815 - loss: 6330.6304 - val_accuracy: 0.9243 - val_auc: 0.8097 - val_loss: 7422.1836
Epoch 53/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9148 - auc: 0.7703 - loss: 7213.8081 - val_accuracy: 0.9236 - val_auc: 0.8103 - val_loss: 6844.7661
Epoch 54/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9157 - auc: 0.7723 - loss: 35599.2070 - val_accuracy: 0.9267 - val_auc: 0.8100 - val_loss: 6994.2886
Epoch 55/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9138 - auc: 0.7719 - loss: 12103.5127 - val_accuracy: 0.9260 - val_auc: 0.8096 - val_loss: 6943.6504
Epoch 56/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9151 - auc: 0.7775 - loss: 24590.5625 - val_accuracy: 0.9236 - val_auc: 0.8106 - val_loss: 5998.3911
Epoch 57/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9154 - auc: 0.7760 - loss: 10599.1201 - val_accuracy: 0.9256 - val_auc: 0.8107 - val_loss: 5343.0410
Epoch 58/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9152 - auc: 0.7645 - loss: 20615.7617 - val_accuracy: 0.9235 - val_auc: 0.8115 - val_loss: 5160.2217
Epoch 59/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9160 - auc: 0.7689 - loss: 27650.6484 - val_accuracy: 0.9243 - val_auc: 0.8110 - val_loss: 6789.5854
Epoch 60/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9160 - auc: 0.7777 - loss: 5997.1528 - val_accuracy: 0.9203 - val_auc: 0.8119 - val_loss: 6741.2090
Epoch 61/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9158 - auc: 0.7710 - loss: 35889.1602 - val_accuracy: 0.9213 - val_auc: 0.8116 - val_loss: 7790.6987
Epoch 62/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9115 - auc: 0.7698 - loss: 1961.0835 - val_accuracy: 0.9263 - val_auc: 0.8115 - val_loss: 3907.6465
Epoch 63/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9156 - auc: 0.7871 - loss: 1561.6453 - val_accuracy: 0.9225 - val_auc: 0.8121 - val_loss: 3241.5513
Epoch 64/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9148 - auc: 0.7841 - loss: 10608.2471 - val_accuracy: 0.9202 - val_auc: 0.8108 - val_loss: 4143.7568
Epoch 65/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9116 - auc: 0.7731 - loss: 4136.5835 - val_accuracy: 0.9236 - val_auc: 0.8118 - val_loss: 2626.5403
Epoch 66/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9150 - auc: 0.7750 - loss: 7807.7432 - val_accuracy: 0.9226 - val_auc: 0.8119 - val_loss: 1802.3544
Epoch 67/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9166 - auc: 0.7816 - loss: 23688.9668 - val_accuracy: 0.9186 - val_auc: 0.8121 - val_loss: 2771.9941
Epoch 68/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9111 - auc: 0.7731 - loss: 22971.5332 - val_accuracy: 0.9216 - val_auc: 0.8128 - val_loss: 3256.8823
Epoch 69/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9151 - auc: 0.7899 - loss: 11138.6562 - val_accuracy: 0.9213 - val_auc: 0.8123 - val_loss: 4440.5977
Epoch 70/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9117 - auc: 0.7742 - loss: 11275.5479 - val_accuracy: 0.9215 - val_auc: 0.8129 - val_loss: 5776.7544
Epoch 71/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9142 - auc: 0.7810 - loss: 230.8383 - val_accuracy: 0.9224 - val_auc: 0.8119 - val_loss: 5776.4370
Epoch 72/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9147 - auc: 0.7865 - loss: 177.8410 - val_accuracy: 0.9221 - val_auc: 0.8124 - val_loss: 5776.3740
Epoch 73/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9128 - auc: 0.7808 - loss: 26702.1562 - val_accuracy: 0.9232 - val_auc: 0.8123 - val_loss: 7841.1880
Epoch 74/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9137 - auc: 0.7828 - loss: 1015.5951 - val_accuracy: 0.9191 - val_auc: 0.8124 - val_loss: 6420.9956
Epoch 75/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9126 - auc: 0.7733 - loss: 7611.0610 - val_accuracy: 0.9184 - val_auc: 0.8123 - val_loss: 6362.1807
Epoch 76/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9120 - auc: 0.7835 - loss: 30925.0664 - val_accuracy: 0.9184 - val_auc: 0.8121 - val_loss: 6362.1270
Epoch 77/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9123 - auc: 0.7883 - loss: 3880.6423 - val_accuracy: 0.9203 - val_auc: 0.8127 - val_loss: 4806.2686
Epoch 78/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9138 - auc: 0.7804 - loss: 28936.7734 - val_accuracy: 0.9174 - val_auc: 0.8130 - val_loss: 4203.6035
Epoch 79/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9154 - auc: 0.7786 - loss: 6243.6914 - val_accuracy: 0.9157 - val_auc: 0.8125 - val_loss: 4466.3545
Epoch 80/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9118 - auc: 0.7864 - loss: 2261.3879 - val_accuracy: 0.9201 - val_auc: 0.8127 - val_loss: 4733.2925
Epoch 81/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9167 - auc: 0.7880 - loss: 6178.6973 - val_accuracy: 0.9156 - val_auc: 0.8130 - val_loss: 4988.9766
Epoch 82/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9123 - auc: 0.7824 - loss: 17701.5566 - val_accuracy: 0.9149 - val_auc: 0.8128 - val_loss: 4989.8994
Epoch 83/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9111 - auc: 0.7872 - loss: 13312.1035 - val_accuracy: 0.9152 - val_auc: 0.8129 - val_loss: 5968.3682
Epoch 84/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9107 - auc: 0.7897 - loss: 2031.9193 - val_accuracy: 0.9168 - val_auc: 0.8129 - val_loss: 5966.5020
Epoch 85/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9119 - auc: 0.7888 - loss: 38382.7812 - val_accuracy: 0.9161 - val_auc: 0.8131 - val_loss: 7338.7935
Epoch 86/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9105 - auc: 0.7966 - loss: 53400.2500 - val_accuracy: 0.9168 - val_auc: 0.8131 - val_loss: 7374.0151
Epoch 87/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9144 - auc: 0.7901 - loss: 6692.1094 - val_accuracy: 0.9163 - val_auc: 0.8138 - val_loss: 5763.2930
Epoch 88/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9123 - auc: 0.7948 - loss: 13895.4355 - val_accuracy: 0.9165 - val_auc: 0.8137 - val_loss: 5795.4438
Epoch 89/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9115 - auc: 0.7907 - loss: 66226.1562 - val_accuracy: 0.9169 - val_auc: 0.8142 - val_loss: 5021.3882
Epoch 90/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9155 - auc: 0.7884 - loss: 5137.3984 - val_accuracy: 0.9167 - val_auc: 0.8145 - val_loss: 6221.4629
Epoch 91/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9135 - auc: 0.7903 - loss: 26310.8945 - val_accuracy: 0.9171 - val_auc: 0.8142 - val_loss: 6267.1318
Epoch 92/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9130 - auc: 0.7826 - loss: 28341.8047 - val_accuracy: 0.9136 - val_auc: 0.8138 - val_loss: 6107.1177
Epoch 93/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9104 - auc: 0.7835 - loss: 346.4720 - val_accuracy: 0.9146 - val_auc: 0.8143 - val_loss: 5589.0649
Epoch 94/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9123 - auc: 0.7845 - loss: 13235.2285 - val_accuracy: 0.9135 - val_auc: 0.8142 - val_loss: 4415.7104
Epoch 95/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9140 - auc: 0.7750 - loss: 7336.2837 - val_accuracy: 0.9130 - val_auc: 0.8142 - val_loss: 3200.5698
Epoch 96/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9117 - auc: 0.7942 - loss: 3576.2583 - val_accuracy: 0.9164 - val_auc: 0.8145 - val_loss: 2803.7502
Epoch 97/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9128 - auc: 0.7941 - loss: 17724.7559 - val_accuracy: 0.9148 - val_auc: 0.8143 - val_loss: 2804.9490
Epoch 98/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9133 - auc: 0.7978 - loss: 247.3069 - val_accuracy: 0.9134 - val_auc: 0.8128 - val_loss: 2989.7827
Epoch 99/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9112 - auc: 0.7936 - loss: 1727.4308 - val_accuracy: 0.9161 - val_auc: 0.8138 - val_loss: 1604.3948
Epoch 100/100
1217/1217 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9103 - auc: 0.7909 - loss: 1204.7074 - val_accuracy: 0.9144 - val_auc: 0.8139 - val_loss: 1535.7665

In [12]:
preds = model.predict(X_test)
results = pd.DataFrame({'id': test_keys, 'TARGET':preds.flatten()})
results.sort_values(by='TARGET', ascending=False)

2370/2370 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step

           id    TARGET
28034   56046  0.825106
37089   74215  0.823287
40626   81235  0.787996
3452     6889  0.774599
14106   28109  0.772400
...       ...       ...
68906  138026  0.000000
53893  108081  0.000000
60157  120574  0.000000
41915   83737  0.000000
25185   50289  0.000000

[75818 rows x 2 columns]

In [13]:
results.to_csv('submission.csv', index=False)